version: 0.2


phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - pwd
      - ls
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running all unit tests"
      - sudo cd New\ Work/puppy_store
      - ls
      - python manage.py test puppy.tests --with-coverage --cover-package=puppy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
